import { images } from "@/config/images";
import type { Ministry } from "@/types";

/* ============================================================
   MINISTRIES — PROVISIONAL NAMES
   ------------------------------------------------------------
   These names are deliberately plain and descriptive. Royalhouse
   Baltimore may well use its own ministry names — swap the `name`,
   `slug` and copy freely, or point `getMinistries()` at a CMS.
   `leader` and `meetingTime` are left empty where the church has
   not supplied them; the cards handle that gracefully.
   ============================================================ */

export const ministries: Ministry[] = [
  {
    id: "worship",
    name: "Worship",
    slug: "worship",
    tagline: "The sound of our house",
    description: [
      "Our worship ministry exists to help a whole room turn its attention to God — not to put on a concert. Musicians, vocalists, sound and lighting all serve the same aim.",
      "If you play, sing or run a desk, there is a place for you here. We audition for readiness and character, not for celebrity.",
    ],
    image: images.worshipTeam.src,
    imageAlt: images.worshipTeam.alt,
    leader: "",
    meetingTime: "",
    meetingLocation: "Royalhouse Baltimore",
    category: "Worship",
    audience: "Musicians, vocalists and production",
    featured: true,
  },
  {
    id: "kids",
    name: "Kids",
    slug: "kids",
    tagline: "Faith that fits small hands",
    description: [
      "Safe, joyful, age-appropriate environments where children meet Jesus for themselves — with stories, songs, questions and a lot of laughing.",
      "Every volunteer is screened and background-checked, and check-in and pick-up are secure so parents can worship without watching the door.",
    ],
    image: images.ministryKids.src,
    imageAlt: images.ministryKids.alt,
    leader: "",
    meetingTime: "",
    meetingLocation: "Kids wing",
    category: "Next Generation",
    audience: "Birth to grade 5",
    featured: true,
  },
  {
    id: "youth",
    name: "Youth",
    slug: "youth",
    tagline: "Loud, honest, going somewhere",
    description: [
      "Middle and high schoolers need more than childcare and more than entertainment. They need adults who take their questions seriously and a faith they can own.",
      "Games, worship, small groups and real conversation — plus a lot of pizza.",
    ],
    image: images.ministryYouth.src,
    imageAlt: images.ministryYouth.alt,
    leader: "",
    meetingTime: "",
    meetingLocation: "Youth space",
    category: "Next Generation",
    audience: "Grades 6–12",
    featured: true,
  },
  {
    id: "young-adults",
    name: "Young Adults",
    slug: "young-adults",
    tagline: "For the in-between years",
    description: [
      "Students, graduates, first jobs, new city, big questions. This is a community for the decade where everything is decided and nothing feels settled.",
      "We meet to eat, study Scripture, pray and figure out faithfulness in real time.",
    ],
    image: images.smallGroup.src,
    imageAlt: images.smallGroup.alt,
    leader: "",
    meetingTime: "",
    meetingLocation: "Homes across Baltimore",
    category: "Adults",
    audience: "Ages 18–30",
  },
  {
    id: "women",
    name: "Women",
    slug: "women",
    tagline: "Strong, seen, sent",
    description: [
      "A community for women in every season — studying, mothering, working, retiring, starting again. Teaching, mentoring and friendships that go past the surface.",
      "Brunches, studies and mentoring pairs through the year.",
    ],
    image: images.ministryWomen.src,
    imageAlt: images.ministryWomen.alt,
    leader: "",
    meetingTime: "",
    meetingLocation: "Royalhouse Baltimore",
    category: "Adults",
    audience: "Women of all ages",
  },
  {
    id: "men",
    name: "Men",
    slug: "men",
    tagline: "Sharpened, not shamed",
    description: [
      "Straight-talking community for men who want to grow up in their faith: accountability without humiliation, and friendships that outlast a season.",
      "Early breakfasts, honest conversation, service projects and prayer.",
    ],
    image: images.ministryMen.src,
    imageAlt: images.ministryMen.alt,
    leader: "",
    meetingTime: "",
    meetingLocation: "Royalhouse Baltimore",
    category: "Adults",
    audience: "Men of all ages",
  },
  {
    id: "prayer",
    name: "Prayer",
    slug: "prayer",
    tagline: "The engine room",
    description: [
      "Nothing significant happens here that was not prayed for first. Our prayer team intercedes for the church, the city and every request that reaches us.",
      "We pray midweek, before services, and privately over the requests you send — in complete confidence.",
    ],
    image: images.prayerCircle.src,
    imageAlt: images.prayerCircle.alt,
    leader: "",
    meetingTime: "",
    meetingLocation: "Royalhouse Baltimore",
    category: "Prayer",
    audience: "Everyone",
    featured: true,
  },
  {
    id: "community-outreach",
    name: "Community Outreach",
    slug: "community-outreach",
    tagline: "Love with its sleeves rolled up",
    description: [
      "Practical love for Baltimore: meals, groceries, school supplies, clean-ups and partnerships with people already serving well in our neighborhoods.",
      "We would rather be known for what we build than for what we say.",
    ],
    image: images.ministryOutreach.src,
    imageAlt: images.ministryOutreach.alt,
    leader: "",
    meetingTime: "",
    meetingLocation: "Across Baltimore",
    category: "Outreach",
    audience: "All ages, families welcome",
  },
  {
    id: "hospitality",
    name: "Welcome & Hospitality",
    slug: "welcome-and-hospitality",
    tagline: "The first face of the church",
    description: [
      "Doors, coffee, directions, seats and warmth. This team decides what a nervous first-time visitor feels in their first ninety seconds — which makes it one of the most important teams we have.",
      "If you are good with people, we need you.",
    ],
    image: images.welcomeLobby.src,
    imageAlt: images.welcomeLobby.alt,
    leader: "",
    meetingTime: "",
    meetingLocation: "Royalhouse Baltimore",
    category: "Serving",
    audience: "Anyone who likes people",
  },
  {
    id: "media",
    name: "Media & Production",
    slug: "media-and-production",
    tagline: "So the message travels",
    description: [
      "Cameras, livestream, editing, photography and social — getting Sunday to the people who could not be in the room, and telling the story of what God is doing here.",
      "Beginners welcome; we will train you.",
    ],
    image: images.eventConference.src,
    imageAlt: images.eventConference.alt,
    leader: "",
    meetingTime: "",
    meetingLocation: "Royalhouse Baltimore",
    category: "Serving",
    audience: "Creatives and technicians",
  },
];

export const ministryCategories = [
  "All",
  "Worship",
  "Next Generation",
  "Adults",
  "Outreach",
  "Prayer",
  "Serving",
] as const;
